"""Emit TypeScript types from the schema registry.

    python manage.py generate_types            # write the file
    python manage.py generate_types --check    # fail if it is out of date

A field's identity used to be a display string repeated in three places that
agreed only by convention, so renaming one silently broke the others and the
breakage surfaced as a frontend bug. Now the backend is the single definition and
the frontend's types are derived from it: rename a field here and the frontend
build fails, at the moment the rename happens.

--check runs in CI so the committed file cannot drift from the schemas.
"""

import difflib
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from funding.models import ApplicationType
from funding.schemas import FieldType, all_schemas

OUTPUT = Path('src/api/schema.generated.ts')

# How a stored answer arrives in JSON. Money and percentages are strings because
# they are Decimals: putting them through a float would lose cents.
TS_TYPE = {
    FieldType.TEXT: 'string',
    FieldType.LONG_TEXT: 'string',
    FieldType.EMAIL: 'string',
    FieldType.PHONE: 'string',
    FieldType.DATE: 'string',
    FieldType.SIGNATURE: 'string',
    FieldType.FILE: 'string',
    FieldType.MONEY: 'string',
    FieldType.PERCENT: 'string',
    FieldType.INTEGER: 'number',
    FieldType.BOOLEAN: 'boolean',
}


def pascal(slug: str) -> str:
    return ''.join(part.capitalize() for part in slug.split('_'))


def field_type(field) -> str:
    if field.type is FieldType.CHOICE:
        return ' | '.join(f"'{value}'" for value in field.choice_values)
    return TS_TYPE[field.type]


def render() -> str:
    lines = [
        '// Generated by `python manage.py generate_types`. Do not edit by hand.',
        '//',
        '// Derived from the schemas in backend/funding/schemas/. Renaming a field',
        '// there breaks this build, which is the point: the frontend holds no',
        '// opinion about what a field is called.',
        '',
        '/** Every kind of application the portal accepts. */',
        'export type ApplicationType =',
    ]
    for value in ApplicationType.values:
        lines.append(f"  | '{value}'")
    lines[-1] += ';'

    lines += [
        '',
        'export const APPLICATION_TYPE_LABELS: Record<ApplicationType, string> = {',
    ]
    for value, label in ApplicationType.choices:
        lines.append(f"  {value}: {label!r}".replace("'", '"') + ',')
    lines += ['};', '']

    lines += [
        "export type FieldType =",
    ]
    for member in FieldType:
        lines.append(f"  | '{member.value}'")
    lines[-1] += ';'

    lines += [
        '',
        '/** One question, as the API describes it. */',
        'export interface SchemaField {',
        '  key: string;',
        '  label: string;',
        '  type: FieldType;',
        '  required: boolean;',
        '  help_text: string;',
        '  section: string;',
        '  choices: Array<{ value: string; label: string }>;',
        '}',
        '',
        'export interface ApplicationSchema {',
        '  slug: ApplicationType;',
        '  label: string;',
        '  sections: string[];',
        '  fields: SchemaField[];',
        '}',
        '',
    ]

    for schema in all_schemas():
        name = f'{pascal(schema.slug)}Answers'
        lines += [
            f'/** Answers for {ApplicationType(schema.slug).label}. */',
            f'export interface {name} {{',
        ]
        for field in schema.fields:
            optional = '' if field.required else '?'
            comment = f'  // {field.help_text}' if field.help_text else ''
            lines.append(f'  {field.key}{optional}: {field_type(field)};{comment}')
        lines += ['}', '']

    lines += ['/** Answer shape for a given application type. */',
              'export interface AnswersByType {']
    for schema in all_schemas():
        lines.append(f'  {schema.slug}: {pascal(schema.slug)}Answers;')
    lines += ['}', '']

    lines += [
        'export type AnswersFor<T extends ApplicationType> = AnswersByType[T];',
        '',
    ]
    return '\n'.join(lines)


class Command(BaseCommand):
    help = 'Generate TypeScript types from the application schemas.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--check', action='store_true',
            help='Exit non-zero if the committed file differs from the schemas.',
        )

    def handle(self, *args, **options):
        # The command runs from backend/; the frontend lives one level up.
        target = (Path.cwd().parent / OUTPUT).resolve()
        generated = render()

        if options['check']:
            if not target.exists():
                raise CommandError(
                    f'{OUTPUT} does not exist. Run: python manage.py generate_types'
                )
            current = target.read_text(encoding='utf-8')
            if current != generated:
                diff = '\n'.join(difflib.unified_diff(
                    current.splitlines(), generated.splitlines(),
                    fromfile='committed', tofile='generated', lineterm='',
                ))
                raise CommandError(
                    f'{OUTPUT} is out of date with the schemas.\n\n{diff}\n\n'
                    'Run: python manage.py generate_types'
                )
            self.stdout.write(self.style.SUCCESS(f'{OUTPUT} is up to date.'))
            return

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated, encoding='utf-8')
        self.stdout.write(self.style.SUCCESS(
            f'Wrote {OUTPUT} — {len(all_schemas())} schemas, '
            f'{sum(len(s.fields) for s in all_schemas())} fields.'
        ))
