"""Emit TypeScript types from the schema registry.

    python manage.py generate_types            # write the file
    python manage.py generate_types --check    # fail if it is out of date

A field's identity used to be a display string repeated in three places that
agreed only by convention, so renaming one silently broke the others and the
breakage surfaced as a frontend bug. Now the backend is the single definition and
the frontend's types are derived from it: rename a field here and the frontend
build fails, at the moment the rename happens.

--check runs in CI so the committed file cannot drift from the schemas.
"""

import difflib
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

from funding.models import (
    AWARDED_STATUSES, DECIDED_STATUSES, ApplicationEvent, ApplicationStatus,
    ApplicationType, FundingStream,
)
from funding.schemas import FieldType, all_schemas
from funding.services.workflow import ALLOWED_ACTIONS, RESULTING_STATUS

OUTPUT = Path('src/api/schema.generated.ts')

# How a stored answer arrives in JSON. Money and percentages are strings because
# they are Decimals: putting them through a float would lose cents.
TS_TYPE = {
    FieldType.TEXT: 'string',
    FieldType.LONG_TEXT: 'string',
    FieldType.EMAIL: 'string',
    FieldType.PHONE: 'string',
    FieldType.DATE: 'string',
    FieldType.SIGNATURE: 'string',
    FieldType.FILE: 'string',
    FieldType.MONEY: 'string',
    FieldType.PERCENT: 'string',
    FieldType.INTEGER: 'number',
    FieldType.BOOLEAN: 'boolean',
    # Only ever true — the server refuses an unconfirmed declaration — but it
    # travels as a boolean like any other tick.
    FieldType.CONFIRM: 'boolean',
    # Sent as a string, never returned: the server keeps it out of answers.
    FieldType.SIN: 'string',
    # The document references, one per attached file.
    FieldType.FILES: 'string[]',
}


def pascal(slug: str) -> str:
    return ''.join(part.capitalize() for part in slug.split('_'))


def field_type(field) -> str:
    if field.type is FieldType.CHOICE:
        return ' | '.join(f"'{value}'" for value in field.choice_values)
    # A table's rows are typed from its own columns, so a column renamed in the
    # schema breaks the frontend build exactly as a field does.
    if field.type is FieldType.TABLE:
        cells = '; '.join(
            f'{column.key}{"" if column.required else "?"}: {field_type(column)}'
            for column in field.columns
        )
        return f'Array<{{ {cells} }}>'
    return TS_TYPE[field.type]


def render() -> str:
    lines = [
        '// Generated by `python manage.py generate_types`. Do not edit by hand.',
        '//',
        '// Derived from the schemas in backend/funding/schemas/. Renaming a field',
        '// there breaks this build, which is the point: the frontend holds no',
        '// opinion about what a field is called.',
        '',
        '/** Every kind of application the portal accepts. */',
        'export type ApplicationType =',
    ]
    for value in ApplicationType.values:
        lines.append(f"  | '{value}'")
    lines[-1] += ';'

    lines += [
        '',
        'export const APPLICATION_TYPE_LABELS: Record<ApplicationType, string> = {',
    ]
    for value, label in ApplicationType.choices:
        lines.append(f"  {value}: {label!r}".replace("'", '"') + ',')
    lines += ['};', '']

    lines += [
        "export type FieldType =",
    ]
    for member in FieldType:
        lines.append(f"  | '{member.value}'")
    lines[-1] += ';'

    lines += [
        '',
        '/** One question, as the API describes it. */',
        'export interface SchemaField {',
        '  key: string;',
        '  label: string;',
        '  type: FieldType;',
        '  required: boolean;',
        '  help_text: string;',
        '  section: string;',
        '  /** Worked out by the server from the other answers. Never rendered',
        '   *  as an input, and any value sent for one is discarded. */',
        '  computed: boolean;',
        '  /** Split off at submission and never returned, so a form opened on a',
        '   *  stored application has no value for it. Blank means unchanged —',
        '   *  required, it would hold Save disabled on every edit. */',
        '  private: boolean;',
        '  /** The most rows or files this accepts. 0 means no limit. */',
        '  max_items: number;',
        "  /** Opens on today's date — the day a declaration is being signed.",
        '   *  Filled by the client, so a guest submission gets it too, and it',
        '   *  stays editable like any other answer. */',
        '  defaults_to_today: boolean;',
        '  choices: Array<{ value: string; label: string }>;',
        "  /** A table field's columns. Empty for every other type. */",
        '  columns: SchemaField[];',
        '}',
        '',
        'export interface ApplicationSchema {',
        '  slug: ApplicationType;',
        '  label: string;',
        '  /** One line saying what this application is for. */',
        '  summary: string;',
        '  /** False where only the portal itself may create one — the',
        '   *  enrolment verification is the registrar\'s form, reached from an',
        '   *  emailed link. Filter the "apply" list on this. */',
        '  apply_in_portal: boolean;',
        '  sections: string[];',
        '  fields: SchemaField[];',
        '}',
        '',
    ]

    for schema in all_schemas():
        name = f'{pascal(schema.slug)}Answers'
        lines += [
            f'/** Answers for {ApplicationType(schema.slug).label}. */',
            f'export interface {name} {{',
        ]
        for field in schema.fields:
            optional = '' if field.required else '?'
            comment = f'  // {field.help_text}' if field.help_text else ''
            lines.append(f'  {field.key}{optional}: {field_type(field)};{comment}')
        lines += ['}', '']

    lines += [
        '/** The sections each form declares, in order.',
        ' *',
        ' * Emitted so the client can be checked against them. Steps are built',
        ' * by naming sections (see features/applications/Apply.tsx), and a',
        ' * section a step does not name is not rendered at all — the questions',
        ' * simply vanish from the form while everything still passes. */',
        'export const APPLICATION_SECTIONS: Record<ApplicationType, string[]> = {',
    ]
    for schema in all_schemas():
        sections = ', '.join(f'{name!r}' for name in schema.sections).replace("'", '"')
        lines.append(f'  {schema.slug}: [{sections}],')
    lines += ['};', '']

    # ── The workflow, as the client needs to know it ──
    #
    # These three were written out by hand in api/client.ts and
    # features/applications/ApplicationDetail.tsx. They are backend enums, and
    # they drifted exactly as a display string once did: the office gained the
    # ability to approve a reviewed application without forwarding it first,
    # the server accepted it, and the button was never added — so the feature
    # existed over HTTP and not in a browser.
    lines += ['/** Where an application can be in its life. */',
              'export type ApplicationStatus =']
    for value in ApplicationStatus.values:
        lines.append(f"  | '{value}'")
    lines[-1] += ';'
    lines.append('')

    lines += ['/** What can be recorded against an application.',
              ' *',
              ' * `amended` is deliberately absent: the office correcting an',
              ' * application is not a step through review, and it is posted to a',
              " * different endpoint. */",
              'export type TransitionAction =']
    for action in ApplicationEvent.Action.values:
        if action in RESULTING_STATUS:
            lines.append(f"  | '{action}'")
    lines[-1] += ';'
    lines.append('')

    lines += [
        '/** Which actions may follow a given status.',
        ' *',
        ' * What the workflow permits next. *Who* may take one of them is a',
        ' * separate question, and only the server answers it. */',
        'export const NEXT_ACTIONS: Record<ApplicationStatus, TransitionAction[]> = {',
    ]
    for status in ApplicationStatus.values:
        allowed = ', '.join(
            f'{str(action)!r}' for action in sorted(ALLOWED_ACTIONS.get(status, set()))
        ).replace("'", '"')
        lines.append(f'  {status}: [{allowed}],')
    lines += ['};', '']

    lines += [
        '/** Statuses in which the current decision is money the office has',
        ' *  committed to. Outside these an application has a *pricing*, and the',
        ' *  server reports its awarded_total as 0.00. */',
        'export const AWARDED_STATUSES: ApplicationStatus[] = ['
        + ', '.join(f"'{v}'" for v in AWARDED_STATUSES) + '];',
        '',
        '/** Statuses in which somebody has decided. Its answers are the record',
        ' *  the decision was made from, and the office takes no further action',
        ' *  that changes what it says or asks anybody a question about it. */',
        'export const DECIDED_STATUSES: ApplicationStatus[] = ['
        + ', '.join(f"'{v}'" for v in DECIDED_STATUSES) + '];',
        '',
    ]

    lines += ['/** Which pot the money comes from. */',
              'export type FundingStream =']
    for value in FundingStream.values:
        lines.append(f"  | '{value}'")
    lines[-1] += ';'
    lines.append('')

    # Emitted rather than written out in the component that filters by stream:
    # a label typed in the client is a second name for the same thing, and this
    # system has already been bitten by a display string deciding what a stream
    # was.
    lines += ['export const FUNDING_STREAM_LABELS: Record<FundingStream, string> = {']
    for value, label in FundingStream.choices:
        lines.append(f"  {value}: {label!r}".replace("'", '"') + ',')
    lines += ['};', '']

    lines += ['/** Answer shape for a given application type. */',
              'export interface AnswersByType {']
    for schema in all_schemas():
        lines.append(f'  {schema.slug}: {pascal(schema.slug)}Answers;')
    lines += ['}', '']

    lines += [
        'export type AnswersFor<T extends ApplicationType> = AnswersByType[T];',
        '',
    ]
    return '\n'.join(lines)


class Command(BaseCommand):
    help = 'Generate TypeScript types from the application schemas.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--check', action='store_true',
            help='Exit non-zero if the committed file differs from the schemas.',
        )

    def handle(self, *args, **options):
        # Anchored to the project, not to the working directory. Resolving
        # against cwd meant running this from the repository root wrote the
        # file to the repository's *parent* and reported success, so the
        # committed types silently never changed.
        target = (Path(settings.BASE_DIR).parent / OUTPUT).resolve()
        generated = render()

        if options['check']:
            if not target.exists():
                raise CommandError(
                    f'{OUTPUT} does not exist. Run: python manage.py generate_types'
                )
            current = target.read_text(encoding='utf-8')
            if current != generated:
                diff = '\n'.join(difflib.unified_diff(
                    current.splitlines(), generated.splitlines(),
                    fromfile='committed', tofile='generated', lineterm='',
                ))
                raise CommandError(
                    f'{OUTPUT} is out of date with the schemas.\n\n{diff}\n\n'
                    'Run: python manage.py generate_types'
                )
            self.stdout.write(self.style.SUCCESS(f'{OUTPUT} is up to date.'))
            return

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated, encoding='utf-8')
        self.stdout.write(self.style.SUCCESS(
            f'Wrote {OUTPUT} — {len(all_schemas())} schemas, '
            f'{sum(len(s.fields) for s in all_schemas())} fields.'
        ))
