# Generated by Django 5.2.13 on 2026-04-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_duplicatedetectionlog'),
        ('forms', '0007_midsemesterchange_applicationdeadline_formsubmission_deadline'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='duplicatedetectionlog',
            name='api_duplica_submiss_idx',
        ),
        migrations.RenameIndex(
            model_name='duplicatedetectionlog',
            new_name='api_duplica_identif_2cb9ea_idx',
            old_name='api_duplica_identif_idx',
        ),
        migrations.RemoveField(
            model_name='duplicatedetectionlog',
            name='submission_id',
        ),
        migrations.AddField(
            model_name='duplicatedetectionlog',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_logs', to='forms.formsubmission'),
        ),
    ]
