# Generated by Django 5.2.13 on 2026-04-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_duplicatedetectionlog_api_duplica_submiss_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='duplicatedetectionlog',
            new_name='duplicate_d_identif_2109f6_idx',
            old_name='api_duplica_identif_2cb9ea_idx',
        ),
        migrations.AlterModelTable(
            name='appeal',
            table='appeals',
        ),
        migrations.AlterModelTable(
            name='application',
            table='student_applications',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_logs',
        ),
        migrations.AlterModelTable(
            name='document',
            table='application_documents',
        ),
        migrations.AlterModelTable(
            name='duplicatedetectionlog',
            table='duplicate_detection_logs',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='policyhistory',
            table='policy_history',
        ),
        migrations.AlterModelTable(
            name='policysetting',
            table='policy_settings',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profiles',
        ),
        migrations.AlterModelTable(
            name='shareablelink',
            table='shareable_links',
        ),
        migrations.AlterModelTable(
            name='userdocument',
            table='user_documents',
        ),
    ]
