# Generated by Django 5.2.13 on 2026-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_api_duplica_identif_2cb9ea_idx_duplicate_d_identif_2109f6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policysetting',
            name='unit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
