# Generated by Django 5.2.13 on 2026-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_increase_policysetting_unit_maxlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, upload_to='application_docs/'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(max_length=255, upload_to='user_documents/'),
        ),
    ]
