# Generated by Django 5.2.13 on 2026-05-04 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userdocument_options_alter_policysetting_id'),
        ('forms', '0014_form_b_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='forms.formsubmission'),
        ),
    ]
