# Generated by Django 5.2.13 on 2026-06-22 13:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_appeal_escalation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(max_length=512, upload_to=api.models._user_document_path),
        ),
    ]
