# Generated by Django 5.2.13 on 2026-08-23 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_eligibility_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('institution_location', models.CharField(blank=True, max_length=255)),
                ('institution_phone', models.CharField(blank=True, max_length=32)),
                ('registrar_email', models.EmailField(blank=True, max_length=254)),
                ('student_number', models.CharField(blank=True, max_length=64)),
                ('program', models.CharField(blank=True, max_length=255)),
                ('credential_level', models.CharField(blank=True, max_length=32)),
                ('learning_style', models.CharField(blank=True, max_length=32)),
                ('course_load', models.CharField(blank=True, max_length=32)),
                ('program_start', models.DateField(blank=True, null=True)),
                ('program_end', models.DateField(blank=True, null=True)),
                ('program_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('program_length_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dependent_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrolment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrolment_profile',
            },
        ),
    ]
