# Generated by Django 5.2.13 on 2026-04-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='program',
            table='programs',
        ),
    ]
