# Generated by Django 5.2.13 on 2026-08-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('received', 'Application received'), ('action_needed', 'Something is needed from you'), ('approved', 'Approved'), ('declined', 'Declined'), ('general', 'General')], default='general', max_length=24),
        ),
    ]
