# Generated by Django 5.2.13 on 2026-08-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('received', 'Application received'), ('action_needed', 'Something is needed from you'), ('approved', 'Approved'), ('declined', 'Declined'), ('amended', 'Changed by the office'), ('general', 'General')], default='general', max_length=24),
        ),
    ]
