# Generated by Django 5.2.13 on 2026-08-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='attachment',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
