# Generated by Django 5.2.13 on 2026-08-09 16:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('admission', 'Admission Application'), ('enrollment_verification', 'Enrollment Verification'), ('continuing_funding', 'Continuing Funding'), ('appeal', 'Appeal / Reconsideration'), ('travel', 'Travel & Emergency Assistance'), ('practicum', 'Practicum Placement Allowance'), ('graduation_bursary', 'Graduation Bursary'), ('summer_student', 'Summer Student Employment'), ('hardship_bursary', 'Hardship Bursary'), ('academic_scholarship', 'Academic Scholarship')], max_length=32)),
                ('stream', models.CharField(choices=[('psssp', 'C-DFN PSSSP'), ('ucepp', 'C-DFN UCEPP'), ('dggr', 'DGGR Bursaries')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('info_requested', 'More Information Requested'), ('awaiting_decision', 'Awaiting Director Decision'), ('approved', 'Approved'), ('declined', 'Declined'), ('sent_to_finance', 'Sent to Finance')], default='submitted', max_length=24)),
                ('schema_slug', models.CharField(max_length=64)),
                ('answers', models.JSONField(default=dict)),
                ('office_notes', models.JSONField(blank=True, default=dict)),
                ('awarded_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.CharField(blank=True, max_length=16)),
                ('semester', models.CharField(blank=True, max_length=16)),
                ('submitted_after_deadline', models.BooleanField(default=False)),
                ('late_approved_at', models.DateTimeField(blank=True, null=True)),
                ('residency_flag', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('late_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('psssp', 'C-DFN PSSSP'), ('ucepp', 'C-DFN UCEPP'), ('dggr', 'DGGR Bursaries')], max_length=16)),
                ('academic_year', models.CharField(max_length=16)),
                ('semester', models.CharField(max_length=16)),
                ('closes_at', models.DateTimeField()),
                ('late_allowed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'application_deadline',
                'ordering': ('-closes_at',),
                'constraints': [models.UniqueConstraint(fields=('stream', 'academic_year', 'semester'), name='uniq_deadline')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('info_requested', 'Information Requested'), ('info_provided', 'Information Provided'), ('forwarded', 'Forwarded to Director'), ('approved', 'Approved'), ('declined', 'Declined'), ('sent_to_finance', 'Sent to Finance')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='funding.application')),
            ],
            options={
                'db_table': 'application_event',
                'ordering': ('occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('living', 'Living Allowance'), ('books', 'Books & Supplies'), ('travel', 'Travel'), ('bursary', 'Bursary'), ('scholarship', 'Scholarship'), ('back_pay', 'Back Pay')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent_to_finance', 'Sent to Finance'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('reference', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('sent_to_finance_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='funding.application')),
                ('sent_to_finance_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'award',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EnrollmentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed'), ('expired', 'Expired')], default='requested', max_length=16)),
                ('confirmed_enrolled', models.BooleanField(blank=True, null=True)),
                ('confirmed_course_load', models.CharField(blank=True, max_length=32)),
                ('registrar_name', models.CharField(blank=True, max_length=255)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_verification', to='funding.application')),
            ],
            options={
                'db_table': 'enrollment_verification',
            },
        ),
        migrations.CreateModel(
            name='PolicySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_setting',
                'ordering': ('section', 'key'),
                'constraints': [models.UniqueConstraint(fields=('section', 'key'), name='uniq_policy_setting')],
            },
        ),
        migrations.CreateModel(
            name='PolicyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='funding.policysetting')),
            ],
            options={
                'db_table': 'policy_change',
                'ordering': ('-effective_date',),
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='funding.application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supporting_document',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-submitted_at'], name='application_status_4f4d57_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['type', 'status'], name='application_type_720f78_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['stream', 'status'], name='application_stream_14182f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', '-submitted_at'], name='application_student_8b830e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['application', 'occurred_at'], name='application_applica_7f91c3_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['application', 'category'], name='award_applica_284c75_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['status', '-created_at'], name='award_status_16b0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentverification',
            index=models.Index(fields=['token'], name='enrollment__token_3aa58b_idx'),
        ),
        migrations.AddIndex(
            model_name='policychange',
            index=models.Index(fields=['setting', 'effective_date'], name='policy_chan_setting_f91bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['application', 'field_key'], name='supporting__applica_3efea6_idx'),
        ),
    ]
