# Generated by Django 5.2.13 on 2026-08-09 22:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('admission', 'Admission Application'), ('enrollment_verification', 'Enrollment Verification'), ('continuing_funding', 'Continuing Funding'), ('appeal', 'Appeal / Reconsideration'), ('travel', 'Travel & Emergency Assistance'), ('practicum', 'Practicum Placement Allowance'), ('graduation_bursary', 'Graduation Bursary'), ('emergency_relief', 'Emergency Relief'), ('hardship_bursary', 'Hardship Bursary'), ('academic_scholarship', 'Academic Scholarship')], max_length=32)),
                ('stream', models.CharField(choices=[('psssp', 'C-DFN PSSSP'), ('ucepp', 'C-DFN UCEPP'), ('dggr', 'DGGR Bursaries')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('info_requested', 'More Information Requested'), ('awaiting_decision', 'Awaiting Director Decision'), ('approved', 'Approved'), ('declined', 'Declined'), ('sent_to_finance', 'Sent to Finance')], default='draft', max_length=24)),
                ('schema_slug', models.CharField(max_length=64)),
                ('answers', models.JSONField(default=dict)),
                ('office_notes', models.JSONField(blank=True, default=dict)),
                ('awarded_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.CharField(blank=True, max_length=16)),
                ('semester', models.CharField(blank=True, max_length=16)),
                ('submitted_after_deadline', models.BooleanField(default=False)),
                ('late_approved_at', models.DateTimeField(blank=True, null=True)),
                ('residency_flag', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('late_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='ActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('approve', 'Approve application'), ('decline', 'Decline application'), ('confirm_payment', 'Confirm payment issued')], max_length=24)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('issued_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tokens', to='funding.application')),
            ],
            options={
                'db_table': 'action_token',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('psssp', 'C-DFN PSSSP'), ('ucepp', 'C-DFN UCEPP'), ('dggr', 'DGGR Bursaries')], max_length=16)),
                ('academic_year', models.CharField(max_length=16)),
                ('semester', models.CharField(max_length=16)),
                ('closes_at', models.DateTimeField()),
                ('late_allowed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'application_deadline',
                'ordering': ('-closes_at',),
                'constraints': [models.UniqueConstraint(fields=('stream', 'academic_year', 'semester'), name='uniq_deadline')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('info_requested', 'Information Requested'), ('info_provided', 'Information Provided'), ('forwarded', 'Forwarded to Director'), ('approved', 'Approved'), ('declined', 'Declined'), ('sent_to_finance', 'Sent to Finance')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='funding.application')),
            ],
            options={
                'db_table': 'application_event',
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('action', models.CharField(max_length=128)),
                ('detail', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='funding.application')),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'db_table': 'audit_entry',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='AwardDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_set_version', models.PositiveIntegerField(help_text='Copied so the version survives independently of the rule set.')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inputs', models.JSONField(default=dict)),
                ('trace', models.JSONField(default=dict, help_text='Every rule considered, whether it fired, and why.')),
                ('is_complete', models.BooleanField(default=True, help_text='False when a rate a rule needed was not configured.')),
                ('is_current', models.BooleanField(default=True)),
                ('priced_on', models.DateField(blank=True, help_text='The date whose rates applied — the submission date, not today.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='funding.application')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='funding.awarddecision')),
            ],
            options={
                'db_table': 'award_decision',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(blank=True, help_text='The rule that produced this line, for the audit trail.', max_length=64)),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('living', 'Living Allowance'), ('books', 'Books & Supplies'), ('travel', 'Travel'), ('bursary', 'Bursary'), ('scholarship', 'Scholarship'), ('back_pay', 'Back Pay')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent_to_finance', 'Sent to Finance'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('reference', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('sent_to_finance_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='funding.application')),
                ('sent_to_finance_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='funding.awarddecision')),
            ],
            options={
                'db_table': 'award',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EnrollmentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed'), ('expired', 'Expired')], default='requested', max_length=16)),
                ('confirmed_enrolled', models.BooleanField(blank=True, null=True)),
                ('confirmed_course_load', models.CharField(blank=True, max_length=32)),
                ('registrar_name', models.CharField(blank=True, max_length=255)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_verification', to='funding.application')),
            ],
            options={
                'db_table': 'enrollment_verification',
            },
        ),
        migrations.CreateModel(
            name='PolicySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_setting',
                'ordering': ('section', 'key'),
                'constraints': [models.UniqueConstraint(fields=('section', 'key'), name='uniq_policy_setting')],
            },
        ),
        migrations.CreateModel(
            name='PolicyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='funding.policysetting')),
            ],
            options={
                'db_table': 'policy_change',
                'ordering': ('-effective_date',),
            },
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Null means still in force.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rule_set',
                'ordering': ('-effective_from', '-version'),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable identifier, cited in the decision trace.', max_length=64)),
                ('description', models.CharField(help_text='Shown to staff and applicants as the reason for an amount.', max_length=255)),
                ('applies_to_types', models.JSONField(blank=True, default=list, help_text='ApplicationType values. Empty means every type.')),
                ('applies_to_streams', models.JSONField(blank=True, default=list, help_text='FundingStream values. Empty means every stream.')),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Predicate over the application. Empty means always.')),
                ('effect', models.JSONField(help_text='{"kind": ..., ...} naming a calculator and its parameters.')),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('living', 'Living Allowance'), ('books', 'Books & Supplies'), ('travel', 'Travel'), ('bursary', 'Bursary'), ('scholarship', 'Scholarship'), ('back_pay', 'Back Pay')], help_text='Which kind of award this produces.', max_length=24)),
                ('order', models.PositiveSmallIntegerField(default=100, help_text='Evaluation order. Tuition rules allocate against a shared remaining balance, so their order decides which stream pays first.')),
                ('is_active', models.BooleanField(default=True)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='funding.ruleset')),
            ],
            options={
                'db_table': 'rule',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='awarddecision',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='funding.ruleset'),
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='funding.application')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'share_link',
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='funding.application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supporting_document',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-submitted_at'], name='application_status_4f4d57_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['type', 'status'], name='application_type_720f78_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['stream', 'status'], name='application_stream_14182f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', '-submitted_at'], name='application_student_8b830e_idx'),
        ),
        migrations.AddIndex(
            model_name='actiontoken',
            index=models.Index(fields=['token'], name='action_toke_token_9824ff_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['application', 'occurred_at'], name='application_applica_7f91c3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['-occurred_at'], name='audit_entry_occurre_afdc17_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['actor', '-occurred_at'], name='audit_entry_actor_i_6b1932_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['application', 'category'], name='award_applica_284c75_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['status', '-created_at'], name='award_status_16b0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentverification',
            index=models.Index(fields=['token'], name='enrollment__token_3aa58b_idx'),
        ),
        migrations.AddIndex(
            model_name='policychange',
            index=models.Index(fields=['setting', 'effective_date'], name='policy_chan_setting_f91bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleset',
            index=models.Index(fields=['status', '-effective_from'], name='rule_set_status_0b5f58_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_ruleset_version'),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.UniqueConstraint(fields=('rule_set', 'code'), name='uniq_rule_code'),
        ),
        migrations.AddIndex(
            model_name='awarddecision',
            index=models.Index(fields=['application', '-created_at'], name='award_decis_applica_d19960_idx'),
        ),
        migrations.AddConstraint(
            model_name='awarddecision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('application',), name='one_current_decision_per_application'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['token'], name='share_link_token_2aba36_idx'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['application', 'field_key'], name='supporting__applica_3efea6_idx'),
        ),
    ]
