# Generated by Django 5.2.13 on 2026-08-11 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentverification',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ApplicantIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sin', 'Social Insurance Number')], default='sin', max_length=16)),
                ('ciphertext', models.TextField()),
                ('last_three', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='funding.application')),
            ],
            options={
                'db_table': 'applicant_identifier',
                'constraints': [models.UniqueConstraint(fields=('application', 'kind'), name='one_identifier_per_kind_per_application')],
            },
        ),
    ]
