# Generated by Django 5.2.13 on 2026-08-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_enrollmentverification_answers_applicantidentifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='application',
        ),
        migrations.RemoveField(
            model_name='sharelink',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ActionToken',
        ),
        migrations.DeleteModel(
            name='ShareLink',
        ),
    ]
