# Generated by Django 5.2.13 on 2026-08-09 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_actiontoken_auditentry_sharelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Null means still in force.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rule_set',
                'ordering': ('-effective_from', '-version'),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable identifier, cited in the decision trace.', max_length=64)),
                ('description', models.CharField(help_text='Shown to staff and applicants as the reason for an amount.', max_length=255)),
                ('applies_to_types', models.JSONField(blank=True, default=list, help_text='ApplicationType values. Empty means every type.')),
                ('applies_to_streams', models.JSONField(blank=True, default=list, help_text='FundingStream values. Empty means every stream.')),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Predicate over the application. Empty means always.')),
                ('effect', models.JSONField(help_text='{"kind": ..., ...} naming a calculator and its parameters.')),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('living', 'Living Allowance'), ('books', 'Books & Supplies'), ('travel', 'Travel'), ('bursary', 'Bursary'), ('scholarship', 'Scholarship'), ('back_pay', 'Back Pay')], help_text='Which kind of award this produces.', max_length=24)),
                ('order', models.PositiveSmallIntegerField(default=100, help_text='Evaluation order. Tuition rules allocate against a shared remaining balance, so their order decides which stream pays first.')),
                ('is_active', models.BooleanField(default=True)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='funding.ruleset')),
            ],
            options={
                'db_table': 'rule',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='ruleset',
            index=models.Index(fields=['status', '-effective_from'], name='rule_set_status_0b5f58_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_ruleset_version'),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.UniqueConstraint(fields=('rule_set', 'code'), name='uniq_rule_code'),
        ),
    ]
