# Generated by Django 5.2.13 on 2026-08-09 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_ruleset_rule_ruleset_rule_set_status_0b5f58_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='rule_code',
            field=models.CharField(blank=True, help_text='The rule that produced this line, for the audit trail.', max_length=64),
        ),
        migrations.CreateModel(
            name='AwardDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_set_version', models.PositiveIntegerField(help_text='Copied so the version survives independently of the rule set.')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inputs', models.JSONField(default=dict)),
                ('trace', models.JSONField(default=dict, help_text='Every rule considered, whether it fired, and why.')),
                ('is_complete', models.BooleanField(default=True, help_text='False when a rate a rule needed was not configured.')),
                ('is_current', models.BooleanField(default=True)),
                ('priced_on', models.DateField(blank=True, help_text='The date whose rates applied — the submission date, not today.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='funding.application')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='funding.ruleset')),
                ('superseded_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='funding.awarddecision')),
            ],
            options={
                'db_table': 'award_decision',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='award',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='funding.awarddecision'),
        ),
        migrations.AddIndex(
            model_name='awarddecision',
            index=models.Index(fields=['application', '-created_at'], name='award_decis_applica_d19960_idx'),
        ),
        migrations.AddConstraint(
            model_name='awarddecision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('application',), name='one_current_decision_per_application'),
        ),
    ]
