# Generated by Django 5.2.13 on 2026-08-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_remove_sharelink_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantidentifier',
            name='kind',
            field=models.CharField(choices=[('sin', 'Social Insurance Number'), ('bank_account', 'Bank account')], default='sin', max_length=16),
        ),
    ]
