# Generated by Django 5.2.13 on 2026-08-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_award_rule_code_awarddecision_award_decision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationevent',
            options={'ordering': ('occurred_at', 'id')},
        ),
    ]
