# Generated by Django 5.2.13 on 2026-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_alter_supportingdocument_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('admission', 'Admission Application'), ('enrollment_verification', 'Enrollment Verification'), ('continuing_funding', 'Continuing Funding'), ('appeal', 'Appeal / Reconsideration'), ('travel', 'Travel & Emergency Assistance'), ('practicum', 'Summer Student / Practicum Award'), ('graduation_bursary', 'Graduation Bursary'), ('emergency_relief', 'Emergency Relief'), ('hardship_bursary', 'Emergency Hardship Bursary (Last Resort)'), ('academic_scholarship', 'Academic Scholarship')], max_length=32),
        ),
    ]
