# Generated by Django 5.2.13 on 2026-08-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0010_dispatched_awards_are_paid_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationevent',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('info_requested', 'Information Requested'), ('info_provided', 'Information Provided'), ('forwarded', 'Forwarded to Director'), ('approved', 'Approved'), ('declined', 'Declined'), ('sent_to_finance', 'Sent to Finance'), ('amended', 'Amended by the office')], max_length=24),
        ),
    ]
