# Generated by Django 5.2.13 on 2026-08-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0013_policy_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='detail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
