# Generated by Django 5.2.13 on 2026-08-24 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0014_award_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(help_text='Why the money came back — withdrew, overpaid, returned.', max_length=255)),
                ('repaid_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='funding.award')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'award_repayment',
                'ordering': ('-repaid_on', '-id'),
                'indexes': [models.Index(fields=['award', '-repaid_on'], name='award_repay_award_i_27d0ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year_start', models.DateField(help_text='1 April of the year the report covers.')),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reported_cost',
                'ordering': ('fiscal_year_start', 'label'),
                'constraints': [models.UniqueConstraint(fields=('fiscal_year_start', 'label'), name='uniq_reported_cost')],
            },
        ),
    ]
