// Generated by `python manage.py generate_types`. Do not edit by hand.
//
// Derived from the schemas in backend/funding/schemas/. Renaming a field
// there breaks this build, which is the point: the frontend holds no
// opinion about what a field is called.

/** Every kind of application the portal accepts. */
export type ApplicationType =
  | 'admission'
  | 'enrollment_verification'
  | 'continuing_funding'
  | 'appeal'
  | 'travel'
  | 'practicum'
  | 'graduation_bursary'
  | 'emergency_relief'
  | 'hardship_bursary'
  | 'academic_scholarship';

export const APPLICATION_TYPE_LABELS: Record<ApplicationType, string> = {
  admission: "Admission Application",
  enrollment_verification: "Enrollment Verification",
  continuing_funding: "Continuing Funding",
  appeal: "Appeal / Reconsideration",
  travel: "Travel & Emergency Assistance",
  practicum: "Practicum Placement Allowance",
  graduation_bursary: "Graduation Bursary",
  emergency_relief: "Emergency Relief",
  hardship_bursary: "Hardship Bursary",
  academic_scholarship: "Academic Scholarship",
};

export type FieldType =
  | 'text'
  | 'long_text'
  | 'email'
  | 'phone'
  | 'date'
  | 'money'
  | 'integer'
  | 'percent'
  | 'choice'
  | 'boolean'
  | 'file'
  | 'signature';

/** One question, as the API describes it. */
export interface SchemaField {
  key: string;
  label: string;
  type: FieldType;
  required: boolean;
  help_text: string;
  section: string;
  choices: Array<{ value: string; label: string }>;
}

export interface ApplicationSchema {
  slug: ApplicationType;
  label: string;
  sections: string[];
  fields: SchemaField[];
}

/** Answers for Academic Scholarship. */
export interface AcademicScholarshipAnswers {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  beneficiary_number?: string;
  institution_name: string;
  program: string;
  semester: 'fall' | 'winter' | 'spring' | 'summer';
  academic_year?: string;
  gpa_achieved: string;  // Determines which achievement band applies.
  account_holder?: string;
  transit_number?: string;
  institution_number?: string;
  account_number?: string;
  signature: string;
  doc_transcript: string;
}

/** Answers for Admission Application. */
export interface AdmissionAnswers {
  first_name: string;
  last_name: string;
  preferred_name?: string;
  date_of_birth: string;
  email: string;
  phone?: string;
  beneficiary_number?: string;
  street_address: string;
  city: string;
  province: string;
  postal_code?: string;
  institution_name: string;
  institution_location?: string;
  program: string;
  program_start?: string;
  program_end?: string;
  registrar_email: string;  // Enrollment is confirmed with the institution before tuition is awarded.
  semester: 'fall' | 'winter' | 'spring' | 'summer';
  semester_start: string;
  semester_end: string;
  course_load: 'full_time' | 'part_time';  // Full-time and part-time draw different living allowance rates.
  tuition_requested?: string;
  has_dependents?: boolean;
  dependent_count?: number;
  receives_sfa?: boolean;  // SFA recipients are not eligible for C-DFN tuition or living allowance.
  account_holder?: string;
  transit_number?: string;
  institution_number?: string;
  account_number?: string;
  signature: string;
  doc_transcript: string;
  doc_letter_of_intent: string;
  doc_status_card: string;
  doc_void_cheque: string;
  doc_reference_letter?: string;
}

/** Answers for Appeal / Reconsideration. */
export interface AppealAnswers {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  beneficiary_number?: string;
  original_decision: string;  // Which decision, and roughly when it was received.
  appeal_reason: string;
  additional_information?: string;
  signature: string;
  doc_supporting?: string;
}

/** Answers for Continuing Funding. */
export interface ContinuingFundingAnswers {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  beneficiary_number?: string;
  date_of_birth?: string;
  institution_name: string;
  program: string;
  current_gpa?: string;
  registrar_email?: string;
  semester: 'fall' | 'winter' | 'spring' | 'summer';
  semester_start: string;
  semester_end: string;
  course_load: 'full_time' | 'part_time';
  tuition_requested?: string;
  has_dependents?: boolean;
  dependent_count?: number;
  receives_sfa?: boolean;
  account_holder?: string;
  transit_number?: string;
  institution_number?: string;
  account_number?: string;
  signature: string;
  doc_transcript: string;
  doc_status_card?: string;
}

/** Answers for Emergency Relief. */
export interface EmergencyReliefAnswers {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  beneficiary_number?: string;
  emergency_type: 'medical' | 'bereavement' | 'housing' | 'travel' | 'other';
  emergency_description: string;
  amount_requested: string;
  account_holder?: string;
  transit_number?: string;
  institution_number?: string;
  account_number?: string;
  signature: string;
  doc_supporting?: string;
}

/** Answers for Enrollment Verification. */
export interface EnrollmentVerificationAnswers {
  student_name: string;
  student_number?: string;
  institution_name: string;
  program: string;
  is_enrolled: boolean;
  course_load: 'full_time' | 'part_time';
  semester_start: string;
  semester_end: string;
  confirmed_tuition: string;  // Tuition is funded against this amount, not the estimate given by the student.
  registrar_name: string;
  registrar_title?: string;
  signature: string;
}

/** Answers for Graduation Bursary. */
export interface GraduationBursaryAnswers {
  first_name: string;
  last_name: string;
  email: string;
  beneficiary_number?: string;
  institution_name: string;
  program: string;
  credential: 'high_school_diploma' | 'certificate' | 'trades_certificate' | 'trades_journeyperson' | 'diploma' | 'pilot_licence' | 'bachelors_degree' | 'masters_degree' | 'doctorate';  // Determines the bursary amount.
  graduation_date: string;
  signature: string;
  doc_proof_of_completion: string;
}

/** Answers for Hardship Bursary. */
export interface HardshipBursaryAnswers {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  beneficiary_number?: string;
  hardship_reason: string;
  supporting_details?: string;
  amount_requested: string;
  account_holder?: string;
  transit_number?: string;
  institution_number?: string;
  account_number?: string;
  signature: string;
  doc_supporting?: string;
}

/** Answers for Practicum Placement Allowance. */
export interface PracticumAnswers {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  beneficiary_number?: string;
  institution_name: string;
  program: string;
  placement_location: string;
  placement_start: string;
  placement_end: string;
  weeks_completed?: number;
  supervisor_name?: string;
  supervisor_email?: string;
  amount_requested?: string;
  account_holder?: string;
  transit_number?: string;
  institution_number?: string;
  account_number?: string;
  signature: string;
  doc_placement_letter: string;
}

/** Answers for Travel & Emergency Assistance. */
export interface TravelAnswers {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  beneficiary_number?: string;
  travel_purpose: 'start_of_study' | 'end_of_study' | 'graduation' | 'compassionate';
  travel_date: string;
  travel_from: string;
  travel_to: string;
  amount_requested: string;
  account_holder?: string;
  transit_number?: string;
  institution_number?: string;
  account_number?: string;
  signature: string;
  doc_receipts: string;  // Travel is reimbursed against receipts.
}

/** Answer shape for a given application type. */
export interface AnswersByType {
  academic_scholarship: AcademicScholarshipAnswers;
  admission: AdmissionAnswers;
  appeal: AppealAnswers;
  continuing_funding: ContinuingFundingAnswers;
  emergency_relief: EmergencyReliefAnswers;
  enrollment_verification: EnrollmentVerificationAnswers;
  graduation_bursary: GraduationBursaryAnswers;
  hardship_bursary: HardshipBursaryAnswers;
  practicum: PracticumAnswers;
  travel: TravelAnswers;
}

export type AnswersFor<T extends ApplicationType> = AnswersByType[T];
