# Generated by Django 5.2.13 on 2026-04-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_midsemesterchange_applicationdeadline_formsubmission_deadline'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicationdeadline',
            table='application_deadlines',
        ),
        migrations.AlterModelTable(
            name='form',
            table='forms',
        ),
        migrations.AlterModelTable(
            name='formfield',
            table='form_fields',
        ),
        migrations.AlterModelTable(
            name='formsubmission',
            table='form_submissions',
        ),
        migrations.AlterModelTable(
            name='midsemesterchange',
            table='mid_semester_changes',
        ),
        migrations.AlterModelTable(
            name='submissionanswer',
            table='submission_answers',
        ),
        migrations.AlterModelTable(
            name='submissionnote',
            table='submission_notes',
        ),
    ]
