# Generated by Django 5.2.13 on 2026-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_applicationdeadline_table_alter_form_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('forwarded', 'Forwarded to Director'), ('more_info_required', 'More Info Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
