# Generated by Django 5.2.13 on 2026-04-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_add_more_info_required_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionanswer',
            name='answer_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='submission_files/'),
        ),
    ]
