# Generated by Django 5.2.13 on 2026-05-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_more_info_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'ordering': ['-submitted_at']},
        ),
    ]
