# Generated by Django 5.2.13 on 2026-05-02 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_formsubmission_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='finance_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='finance_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_dispatched_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('forwarded', 'Forwarded to Director'), ('more_info_required', 'More Info Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('sent_to_finance', 'Sent to Finance')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['student', 'status'], name='form_submis_student_3350bf_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='form_submis_status_cb77d9_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', 'student'], name='form_submis_form_id_aa5f42_idx'),
        ),
    ]
