# Generated by Django 5.2.13 on 2026-05-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_finance_dispatch_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('registrar_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent to Registrar'), ('received', 'Received from Registrar'), ('expired', 'Link Expired')], default='sent', max_length=20)),
                ('student_name', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('program', models.CharField(blank=True, max_length=255)),
                ('sem_start', models.CharField(blank=True, max_length=50)),
                ('sem_end', models.CharField(blank=True, max_length=50)),
                ('is_enrolled', models.BooleanField(blank=True, null=True)),
                ('enrollment_status', models.CharField(blank=True, max_length=50)),
                ('course_load_percent', models.IntegerField(blank=True, null=True)),
                ('confirmed_program', models.CharField(blank=True, max_length=255)),
                ('confirmed_sem_start', models.CharField(blank=True, max_length=50)),
                ('confirmed_sem_end', models.CharField(blank=True, max_length=50)),
                ('official_tuition', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registrar_notes', models.TextField(blank=True)),
                ('registrar_name', models.CharField(blank=True, max_length=255)),
                ('registrar_title', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_b', to='forms.formsubmission')),
            ],
            options={
                'db_table': 'form_b_responses',
                'ordering': ['-sent_at'],
            },
        ),
    ]
