# Generated by Django 5.2.13 on 2026-08-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_submissionanswer_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='residency_flag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
