# Generated by Django 5.2.13 on 2026-08-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_formsubmission_residency_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='answers_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='schema_slug',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
