# Generated by Django 5.2.13 on 2026-04-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deline_beneficiary',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_indian_act_registered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province_of_residence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
