# Generated by Django 5.2.13 on 2026-05-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_eligibility_q_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
