# Generated by Django 5.2.13 on 2026-06-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('director', 'Director'), ('ssw', 'Student Support Worker'), ('finance', 'Finance')], default='student', max_length=10),
        ),
    ]
