# Generated by Django 5.2.13 on 2026-06-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_ssw_finance_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='province_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
